version: '3'

services:

  nginx_proxy:
    # image: nginx:latest
    container_name: nginx_proxy
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - meetup_web
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      reverse_proxy:

  meetup_web:
    image: jitsi/web
    container_name: meetup_web
    ports:
        - '${HTTP_PORT}:80'
        - '${HTTPS_PORT}:443'
    volumes:
        - ${CONFIG}/web:/config
    environment:
        - ENABLE_AUTH
        - ENABLE_GUESTS
        - JICOFO_AUTH_USER
        - XMPP_DOMAIN
        - XMPP_AUTH_DOMAIN
        - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
        - XMPP_GUEST_DOMAIN
        - XMPP_MUC_DOMAIN
        - TZ
    networks:
      - meet.jitsi
      - proxy

  # XMPP server
  jitsi_prosody:
    image: jitsi/prosody
    container_name: jitsi_prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ${CONFIG}/prosody:/config
    environment:
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - TZ
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo
    container_name: jitsi_jicofo
    volumes:
      - ${CONFIG}/jicofo:/config
    environment:
      - ENABLE_AUTH
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER=xmpp.meet.jitsi
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JIGASI_BREWERY_MUC
      - TZ
    depends_on:
      - jitsi_prosody
    networks:
        meet.jitsi:

  # Video bridge
  jvb:
    image: jitsi/jvb
    container_name: jitsi_jvb
    ports:
      - '${JVB_PORT}:${JVB_PORT}/udp'
    volumes:
      - ${CONFIG}/jvb:/config
    environment:
      - DOCKER_HOST_ADDRESS
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER=xmpp.meet.jitsi
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_PORT
      - JVB_STUN_SERVERS
      - JICOFO_AUTH_USER
      - TZ
    depends_on:
      - jitsi_prosody
    networks:
      meet.jitsi:

