version: '3'

services:

  nginx_proxy:
    # image: nginx:latest
    container_name: nginx_proxy
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - meetup_web
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      reverse_proxy:

networks:
  meet.jitsi:
  reverse_proxy:
