version: '3.7'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    cmd: |
      quay.io/letsencrypt/letsencrypt:latest \
        certonly \
        -d dailyprime.me \
        -d *.dailyprime.me \
        --manual \
        --preferred-challenges dns \
        --server https://acme-v02.api.letsencrypt.org/directory
networks:
  nginx_network:
