---
version: '3.1'
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/layer4_external/Nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped
