version: '3.1'

services:

  nginx_proxy:
    # image: nginx:latest
    container_name: nginx_proxy
    build: ./
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - web
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    networks:
      reverse_proxy:

networks:
  reverse_proxy:
