---
version: '3.1'

services:

  nginx:
    # image: nginx:latest
    container_name: nginx
    build: ./
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./fullchain.pem:/etc/letsencrypt/live/dougandkathy.com/fullchain.pem:ro
      - ./privkey.pem:/etc/letsencrypt/live/dougandkathy.com/privkey.pem:ro

    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

