version: '3.7'

volumes:
  postgres_files:
    driver: local

services:
  postgres:
    env_file:
      - ../.env_postgres
    build:
      context: $PWD/postgres/
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_files:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      postgres_network:

networks:
  postgres_network:
