version: '3.7'

volumes:
  redis_files:
    driver: local

services:
  redis:
    build: $PWD/redis/
    container_name: redis
    env_file:
      - ../.env_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_files:/var/lib/redis
    networks:
      redis_network:
networks:
  redis_network:
